// export const CivilStudents = [
//     {
//         image:"https://img.freepik.com/premium-photo/happy-young-students-studying-college-library-with-stack-books_21730-4486.jpg",
//         name:"Student1",
//         pin:"21637-Ce-001",
//         id:"1"
//     },
//     {
//         image:"https://www.shutterstock.com/image-photo/young-student-uniform-chalk-board-260nw-620322356.jpg",
//         name:"Student2",
//         pin:"21637-Ce-002",
//         id:"2"
//     },
//     {
//         image:"https://img.freepik.com/premium-photo/happy-young-students-studying-college-library-with-stack-books_21730-4486.jpg",
//         name:"Student3",
//         pin:"21637-Ce-003",
//         id:"3"
//     },
//     {
//         image:"https://www.shutterstock.com/image-photo/young-student-uniform-chalk-board-260nw-620322356.jpg",
//         name:"Student4",
//         pin:"21637-Ce-004",
//         id:"4"
//     },
//     {
//         image:"https://img.freepik.com/premium-photo/happy-young-students-studying-college-library-with-stack-books_21730-4486.jpg",
//         name:"Student5",
//         pin:"21637-Ce-005",
//         id:"5"
//     },
//     {
//         image:"https://www.shutterstock.com/image-photo/young-student-uniform-chalk-board-260nw-620322356.jpg",
//         name:"Student6",
//         pin:"21637-Ce-006",
//         id:"6"
//     },
//     {
//         image:"https://img.freepik.com/premium-photo/happy-young-students-studying-college-library-with-stack-books_21730-4486.jpg",
//         name:"Student7",
//         pin:"21637-Ce-007",
//         id:"7"
//     },
//     {
//         image:"https://www.shutterstock.com/image-photo/young-student-uniform-chalk-board-260nw-620322356.jpg",
//         name:"Student8",
//         pin:"21637-Ce-008",
//         id:"8"
//     }
// ]